export { default as Alert } from './layout/Alert/Alert'
export { default as NavBar } from './layout/NavBar/NavBar'
export { default as Spinner } from './layout/Spinner/Spinner'
export { default as About } from './pages/About/About'
export { default as Home } from './pages/Home/Home'
export { default as Search } from './users/Search/Search'
export { default as User } from './users/User/User'
export { default as UserItem } from './users/UserItem/UserItem'
export { default as Users } from './users/Users/Users'

